### ISSUE TITLE
sigmac does not work

### ISSUE THREAD

**Issue by crackytsi** [Neo23x0/sigma#126]
Hi,
After installing sigmac on my Debian System, the tool fails:

```

pip3 install sigmatools
user@server:~/sigma# sigmac  -h
Traceback (most recent call last):
  File "/usr/local/bin/sigmac", line 27, in <module>
    import sigma.backends as backends
  File "/usr/local/lib/python3.4/dist-packages/sigma/backends.py", line 700
    **min_doc_count
     ^
SyntaxError: invalid Syntax


```

Can you help me here?

**Comment by thomaspatzke** [comment]
Sigmac works with Python >= 3.5, which is available from the current stable (stretch).
