### ISSUE TITLE
Sigmac Converter Failure

### ISSUE THREAD

**Issue by P4T12ICK** [Neo23x0/sigma#419]
Hi,

I found the following issue. The sigmac converter (when installed with pip3) is using the import of auto: "from enum import Enum, auto" (in ...sigma/parser/modifiers/base.py).
As far as I know was the auto function introduced in Python 3.6. Therefore, I would either change the requirements to Python >=3.6 or I wouldn't use the auto function.

Reproduce the failure:
- Spin Up the logger machine from Chris Longs Detection Lab (based on Ubuntu 16.04 with Python 3.5.2)
- Install sigmatools with pip3
- Try to run sigmac --help

Then you will get the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/sigmac", line 25, in <module>
    from sigma.parser.collection import SigmaCollectionParser
  File "/usr/local/lib/python3.5/dist-packages/sigma/parser/collection.py", line 18, in <module>
    from .rule import SigmaParser
  File "/usr/local/lib/python3.5/dist-packages/sigma/parser/rule.py", line 20, in <module>
    from .modifiers import apply_modifiers
  File "/usr/local/lib/python3.5/dist-packages/sigma/parser/modifiers/__init__.py", line 1, in <module>
    from .discovery import modifiers, apply_modifiers
  File "/usr/local/lib/python3.5/dist-packages/sigma/parser/modifiers/discovery.py", line 19, in <module>
    from .base import SigmaModifier
  File "/usr/local/lib/python3.5/dist-packages/sigma/parser/modifiers/base.py", line 17, in <module>
    from enum import Enum, auto
ImportError: cannot import name 'auto'

**Comment by thomaspatzke** [comment]
The setup.py used for packaging of the PyPI release [specifies correctly 3.6 upwards as required Python version](https://github.com/Neo23x0/sigma/blob/master/tools/setup.py#L38). The  problem is the pip version packaged with Ubuntu 16.04, 8.1.1. According to the [documentation for python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) pip versions from 9 recognize this information.
