### ISSUE TITLE
Error with sigmac

### ISSUE THREAD

**Issue by mancharagopan** [Neo23x0/sigma#520]
I am receiving following error when i try to use sigmac,

```
[it@kibana tools]$ ./sigmac -t splunk -c tools/config/generic/sysmon.yml ./rules/windows/process_creation/win_susp_whoami.yml
Traceback (most recent call last):
  File "./sigmac", line 121, in <module>
    scm = SigmaConfigurationManager()
  File "/etc/sigma/tools/sigma/config/collection.py", line 60, in __init__
    self.update()
  File "/etc/sigma/tools/sigma/config/collection.py", line 70, in update
    self.configs[conf_path.stem] = SigmaConfiguration(f)
  File "/etc/sigma/tools/sigma/configuration.py", line 94, in __init__
    config = yaml.safe_load(configyaml)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib64/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib64/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib64/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/etc/sigma/tests/invalid_yaml.yml", line 1, column 9
```
Can anyone help?

**Comment by Neo23x0** [comment]
When you're in the `tools` folder, you should have to use 

```
./sigmac -t splunk -c ./config/generic/sysmon.yml ../rules/windows/process_creation/win_susp_whoami.yml
```

**Comment by mancharagopan** [comment]
I tried the above command but i got an error no such file or directory

```
[it@kibana tools]$ ./sigmac -t splunk -c ./config/generic/sysmon.yml ../rules/windows/process_creation/win_susp_whoami.yml
/usr/bin/env: python3: No such file or directory
```

**Comment by mancharagopan** [comment]
I used following command but got an error,
My Python version 3.4 and PyYAML = 5.1.2, Sigma = 0.6

```
[it@kibana tools]$ python3.4 ./sigmac -t splunk -c ./config/generic/sysmon.yml ../rules/windows/process_creation/win_susp_whoami.yml
Traceback (most recent call last):
  File "./sigmac", line 25, in <module>
    from sigma.parser.collection import SigmaCollectionParser
  File "/opt/sigma/tools/sigma/parser/collection.py", line 18, in <module>
    from .rule import SigmaParser
  File "/opt/sigma/tools/sigma/parser/rule.py", line 20, in <module>
    from .modifiers import apply_modifiers
  File "/opt/sigma/tools/sigma/parser/modifiers/__init__.py", line 1, in <module>
    from .discovery import modifiers, apply_modifiers
  File "/opt/sigma/tools/sigma/parser/modifiers/discovery.py", line 19, in <module>
    from .base import SigmaModifier
  File "/opt/sigma/tools/sigma/parser/modifiers/base.py", line 17, in <module>
    from enum import Enum, auto
ImportError: cannot import name 'auto'
```

**Comment by mancharagopan** [comment]
It's working now. Thank you for the support.
I upgraded python version to 3.6 and install sigma again.
