### ISSUE TITLE
Bug, when create instance class SigmaConfigurationManager

### ISSUE THREAD

**Issue by ayatsyny** [Neo23x0/sigma#736]
When trying to create an instance another path, the have error

```
import os
from sigma.config.collection import SigmaConfigurationManager


BASE_DIR = os.path.abspath(__file__).rsplit('/', 1)[0]
con_dir = BASE_DIR + '/' + os.path.join('tools', 'config')

print(con_dir)
test = SigmaConfigurationManager(paths=con_dir)
```

results:

```
/home/sigma/tools/tools/config
Traceback (most recent call last):
  File "some_example.py", line 12, in <module>
    test = SigmaConfigurationManager(paths=con_dir)
  File "/home/sigma/tools/sigma/config/collection.py", line 60, in __init__
    self.update()
  File "/home/sigma/tools/sigma/config/collection.py", line 67, in update
    for conf_path in path.glob("**/*.yml"):
AttributeError: 'str' object has no attribute 'glob'
```

the same:

```
import os
# from tools.sigma.config.collection import SigmaConfigurationManager
from sigma.config.collection import SigmaConfigurationManager


BASE_DIR = os.path.abspath(__file__).rsplit('/', 1)[0]
con_dir = BASE_DIR + '/' + os.path.join('tools', 'config')

print(con_dir)
test = SigmaConfigurationManager(paths=[con_dir])
```

```
/home/sigma/tools/tools/config
Traceback (most recent call last):
  File "some_example.py", line 10, in <module>
    test = SigmaConfigurationManager(paths=[con_dir])
  File "/home/sigma/tools/sigma/config/collection.py", line 60, in __init__
    self.update()
  File "/home/sigma/tools/sigma/config/collection.py", line 67, in update
    for conf_path in path.glob("**/*.yml"):
AttributeError: 'str' object has no attribute 'glob'
```

**Comment by kevthehermit** [comment]
I had this same issue it looks like

This line is looking for a list of strings
https://github.com/Neo23x0/sigma/blob/578d2f0585b499999de9d4fd1c6bb20dd25b90d2/tools/sigma/config/collection.py#L53

But later It wants a path object which is what is created if paths=None

https://github.com/Neo23x0/sigma/blob/578d2f0585b499999de9d4fd1c6bb20dd25b90d2/tools/sigma/config/collection.py#L67

Something like this would work

```
isinstance(paths, Iterable) and all([type(path) in [pathlib.PosixPath, pathlib.WindowsPath] for path in paths])

```

Then you would 

```
scm = SigmaConfigurationManager([Path("path/to/sigma_configs")])
```

**Comment by kevthehermit** [comment]
Happy to open a PR if this is an acceptable fix
